import { Project } from "@/model/api";

const mockProjects: Project[] = [
  {
    id: "project_a",
    name: "Project Alpha",
    start_date: "2023-01-15",
    end_date: "2023-06-15",
    manager: "John Doe",
    description: "Lorem",
  },
  {
    id: "project_b",
    name: "Project Beta",
    start_date: "2023-03-01",
    end_date: "2023-09-30",
    manager: "Jane Smith",
    description: "Lorem",
  },
  {
    id: "project_c",
    name: "Project Gamma",
    start_date: "2023-07-01",
    end_date: "2023-12-31",
    manager: "Alice Johnson",
    description: "Lorem",
  },
  {
    id: "project_d",
    name: "Project Delta",
    start_date: "2023-02-20",
    end_date: "2023-08-20",
    manager: "George Brown",
    description: "Lorem",
  },
  {
    id: "project_e",
    name: "Project Epsilon",
    start_date: "2023-04-05",
    end_date: "2023-10-15",
    manager: "Michael White",
    description: "Lorem",
  },
  {
    id: "project_f",
    name: "Project Zeta",
    start_date: "2023-05-10",
    end_date: "2023-11-30",
    manager: "Linda Davis",
    description: "Lorem",
  },
  {
    id: "project_g",
    name: "Project Eta",
    start_date: "2023-06-01",
    end_date: "2023-12-01",
    manager: "Robert Harris",
    description: "Lorem",
  },
  {
    id: "project_h",
    name: "Project Theta",
    start_date: "2023-02-28",
    end_date: "2023-09-15",
    manager: "Jessica Martin",
    description: "Lorem",
  },
  {
    id: "project_i",
    name: "Project Iota",
    start_date: "2023-07-15",
    end_date: "2024-01-15",
    manager: "David Clark",
    description: "Lorem",
  },
  {
    id: "project_j",
    name: "Project Kappa",
    start_date: "2023-08-10",
    end_date: "2024-02-28",
    manager: "Emily Rodriguez",
    description: "Lorem",
  },
  {
    id: "project_k",
    name: "Project Lambda",
    start_date: "2023-09-05",
    end_date: "2024-03-01",
    manager: "William Lewis",
    description: "Lorem",
  },
  {
    id: "project_l",
    name: "Project Mu",
    start_date: "2023-10-01",
    end_date: "2024-04-01",
    manager: "Sophia Walker",
    description: "Lorem",
  },
  {
    id: "project_m",
    name: "Project Nu",
    start_date: "2023-11-01",
    end_date: "2024-05-01",
    manager: "Daniel Young",
    description: "Lorem",
  },
  {
    id: "project_n",
    name: "Project Xi",
    start_date: "2023-12-01",
    end_date: "2024-06-01",
    manager: "Olivia King",
    description: "Lorem",
  },
  {
    id: "project_o",
    name: "Project Omicron",
    start_date: "2023-01-25",
    end_date: "2023-07-25",
    manager: "James Scott",
    description: "Lorem",
  },
  {
    id: "project_p",
    name: "Project Pi",
    start_date: "2023-04-15",
    end_date: "2023-10-15",
    manager: "Charlotte Thompson",
    description: "Lorem",
  },
  {
    id: "project_q",
    name: "Project Rho",
    start_date: "2023-05-20",
    end_date: "2023-11-20",
    manager: "Lucas Perez",
    description: "Lorem",
  },
  {
    id: "project_r",
    name: "Project Sigma",
    start_date: "2023-06-30",
    end_date: "2023-12-30",
    manager: "Amelia Lee",
    description: "Lorem",
  },
  {
    id: "project_s",
    name: "Project Tau",
    start_date: "2023-07-20",
    end_date: "2024-01-20",
    manager: "Henry Walker",
    description: "Lorem",
  },
];

export const fetchProjects = (): Promise<Project[]> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockProjects);
    }, 1000);
  });
};
